Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -34,7 +34,7 @@ jobs:
         run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}" > ~/.npmrc
 
       - name: Debug npm token
-        run: cat ~/.npmrc && npm whoami || echo "Auth failed"
+        run: npm whoami || echo "Auth failed"
   
       - name: Install dependencies
         run: npm ci
